/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DynastyRouteImport } from './routes/dynasty'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as MatchRouteImport } from './routes/match'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as TacticsRouteImport } from './routes/tactics'
import { Route as TransfersRouteImport } from './routes/transfers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DynastyRoute = DynastyRouteImport.update({
  id: '/dynasty',
  path: '/dynasty',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const TacticsRoute = TacticsRouteImport.update({
  id: '/tactics',
  path: '/tactics',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dynasty': typeof DynastyRoute
  '/league': typeof LeagueRoute
  '/match': typeof MatchRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/squad': typeof SquadRoute
  '/tactics': typeof TacticsRoute
  '/transfers': typeof TransfersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dynasty': typeof DynastyRoute
  '/league': typeof LeagueRoute
  '/match': typeof MatchRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/squad': typeof SquadRoute
  '/tactics': typeof TacticsRoute
  '/transfers': typeof TransfersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dynasty': typeof DynastyRoute
  '/league': typeof LeagueRoute
  '/match': typeof MatchRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/squad': typeof SquadRoute
  '/tactics': typeof TacticsRoute
  '/transfers': typeof TransfersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dynasty'
    | '/league'
    | '/match'
    | '/profile'
    | '/settings'
    | '/squad'
    | '/tactics'
    | '/transfers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dynasty'
    | '/league'
    | '/match'
    | '/profile'
    | '/settings'
    | '/squad'
    | '/tactics'
    | '/transfers'
  id:
    | '__root__'
    | '/'
    | '/dynasty'
    | '/league'
    | '/match'
    | '/profile'
    | '/settings'
    | '/squad'
    | '/tactics'
    | '/transfers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DynastyRoute: typeof DynastyRoute
  LeagueRoute: typeof LeagueRoute
  MatchRoute: typeof MatchRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SquadRoute: typeof SquadRoute
  TacticsRoute: typeof TacticsRoute
  TransfersRoute: typeof TransfersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dynasty': {
      id: '/dynasty'
      path: '/dynasty'
      fullPath: '/dynasty'
      preLoaderRoute: typeof DynastyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactics': {
      id: '/tactics'
      path: '/tactics'
      fullPath: '/tactics'
      preLoaderRoute: typeof TacticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DynastyRoute: DynastyRoute,
  LeagueRoute: LeagueRoute,
  MatchRoute: MatchRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SquadRoute: SquadRoute,
  TacticsRoute: TacticsRoute,
  TransfersRoute: TransfersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
